// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MoodSnap",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "MoodSnap",
            targets: ["AppModule"],
            teamIdentifier: "ULMGDWJT46",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/danielgindi/Charts", "3.1.1"..<"4.0.0"),
        .package(url: "https://github.com/techprimate/TPPDF", "2.3.5"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Charts", package: "Charts"),
                .product(name: "TPPDF", package: "TPPDF")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
